import {Link,useSearchParams} from 'react-router-dom'; import {AlertTriangle,CheckCircle2,Download,LifeBuoy,Receipt,User,Package} from 'lucide-react'; import Seo from '../components/Seo'; import {Faq as FaqSection} from './Home';
const copy:Record<string,{title:string;desc:string;body:string[]}>={
tentang:{title:'Tentang Sobri',desc:'Kami membantu lebih banyak orang bekerja secara cerdas.',body:['Sobri adalah toko produk digital Indonesia yang mengkurasi sumber daya praktis untuk pebisnis, kreator, dan profesional.','Setiap produk dipilih berdasarkan kegunaan, kejelasan, dan kemudahan penerapannya. Kami percaya alat yang tepat dapat menghemat waktu dan membuka ruang untuk pertumbuhan.']},
kontak:{title:'Hubungi Sobri',desc:'Ada pertanyaan? Tim kami siap membantu.',body:['Kirim email ke halo@sobri.id atau WhatsApp pada jam kerja Senin–Jumat pukul 09.00–17.00 WIB.','Cantumkan nomor pesanan untuk bantuan terkait transaksi. Kami biasanya membalas dalam satu hari kerja.']},
'cara-pembelian':{title:'Cara Pembelian',desc:'Tiga langkah mudah untuk mendapatkan produk.',body:['1. Pilih produk dan pelajari detail, format file, serta lisensinya.','2. Masukkan data kontak lalu bayar melalui kanal resmi Midtrans.','3. Setelah pembayaran terverifikasi, akses produk dari email atau dashboard akun.']},
'kebijakan-privasi':{title:'Kebijakan Privasi',desc:'Cara Sobri melindungi informasi Anda.',body:['Kami mengumpulkan data yang diperlukan untuk memproses pesanan, menyediakan akses, mencegah penyalahgunaan, dan memberikan dukungan.','Data pembayaran diproses oleh gateway dan tidak disimpan oleh Sobri. Anda dapat meminta akses atau penghapusan data dengan menghubungi kami.']},
'syarat-ketentuan':{title:'Syarat dan Ketentuan',desc:'Ketentuan penggunaan layanan dan produk Sobri.',body:['Dengan membeli, Anda menyatakan data transaksi benar serta menyetujui lisensi produk terkait. Dilarang membagikan, menjual kembali, atau mengunggah file tanpa izin.','Akses dapat ditangguhkan bila terindikasi penyalahgunaan. Harga dan promosi dapat berubah, tetapi tidak memengaruhi pesanan yang sudah dibayar.']},
'kebijakan-pengembalian-dana':{title:'Kebijakan Pengembalian Dana',desc:'Perlindungan pembelian produk digital.',body:['Karena produk dikirim secara digital, perubahan pikiran tidak termasuk alasan refund. Permintaan dapat ditinjau bila file rusak, tidak dapat diakses, atau secara material tidak sesuai deskripsi.','Ajukan dalam 7 hari sejak transaksi dengan nomor pesanan dan bukti kendala. Proses peninjauan maksimal 5 hari kerja.']},
lisensi:{title:'Lisensi Produk',desc:'Gunakan karya digital secara bertanggung jawab.',body:['Lisensi pribadi berlaku untuk satu pengguna. Lisensi komersial terbatas mengizinkan penggunaan dalam karya akhir untuk klien, tetapi file sumber tidak boleh dijual atau dibagikan ulang.','Rincian lisensi pada halaman produk berlaku apabila terdapat perbedaan dengan ketentuan umum ini.']}
};
export function StaticPage({type}:{type:string}){const c=copy[type]||copy.tentang;return <section className="section container max-w-4xl"><Seo title={c.title} description={c.desc}/><p className="eyebrow">Sobri</p><h1 className="mt-3 text-4xl font-black text-navy-950">{c.title}</h1><p className="mt-4 text-lg text-slate-500">{c.desc}</p><div className="mt-10 space-y-5 rounded-2xl border p-7">{c.body.map(x=><p className="leading-8 text-slate-600" key={x}>{x}</p>)}</div></section>}
export function FAQ(){return <><Seo title="FAQ" description="Jawaban pertanyaan umum pelanggan Sobri."/><FaqSection/></>}
export function PaymentResult({success}:{success:boolean}){const [q]=useSearchParams(),demo=q.get('demo');return <section className="section container max-w-xl text-center"><Seo title={success?'Pembayaran Diproses':'Pembayaran Gagal'} description="Status transaksi Sobri."/>{success?<CheckCircle2 className="mx-auto text-emerald-500" size={64}/>:<AlertTriangle className="mx-auto text-rose-500" size={64}/>}<h1 className="mt-6 text-3xl font-black">{success?'Pesanan telah dibuat':'Pembayaran belum berhasil'}</h1><p className="mt-3 text-slate-500">{success?(demo?'Ini adalah simulasi mode demo—tidak ada pembayaran atau akses produk nyata yang diaktifkan.':'Kami sedang memverifikasi pembayaran melalui gateway. Akses aktif hanya setelah webhook terkonfirmasi.'):'Tidak ada dana yang tercatat. Silakan ulangi pembayaran atau hubungi bantuan.'}</p><Link to={success?'/akun':'/checkout'} className="btn btn-primary mt-7">{success?'Lihat Akun':'Coba Lagi'}</Link></section>}
export function Auth({register=false}:{register?:boolean}){return <section className="section container max-w-md"><Seo title={register?'Daftar Akun':'Masuk'} description="Akses akun pelanggan Sobri."/><div className="card p-7"><h1 className="text-3xl font-black">{register?'Buat Akun':'Selamat Datang'}</h1><p className="mt-2 text-sm text-slate-500">{register?'Simpan semua pembelian dalam satu tempat.':'Masuk untuk mengakses produk Anda.'}</p><form className="mt-7 space-y-4" onSubmit={e=>e.preventDefault()}>{register&&<label className="block text-sm font-bold">Nama lengkap<input className="input mt-2" required/></label>}<label className="block text-sm font-bold">Email<input className="input mt-2" type="email" required/></label><label className="block text-sm font-bold">Kata sandi<input className="input mt-2" type="password" minLength={8} required/></label><button className="btn btn-primary w-full">{register?'Daftar':'Masuk'}</button></form><button className="btn btn-outline mt-3 w-full">Kirim tautan masuk aman</button><p className="mt-5 text-center text-sm">{register?'Sudah punya akun?':'Belum punya akun?'} <Link className="font-bold text-brand" to={register?'/masuk':'/daftar'}>{register?'Masuk':'Daftar'}</Link></p></div></section>}
export function Account(){return <section className="section container"><Seo title="Akun Saya" description="Kelola profil, pesanan, dan produk Sobri."/><h1 className="text-4xl font-black">Akun Saya</h1><div className="mt-8 grid gap-5 md:grid-cols-4">{([[User,'Profil','Lengkapi data akun'],[Receipt,'Pesanan','Lihat status pembayaran'],[Package,'Produk Saya','Akses pembelian'],[LifeBuoy,'Bantuan','Hubungi tim Sobri']] as const).map(([I,t,d])=><Link to={t==='Pesanan'?'/akun/pesanan':'/akun'} className="card p-6" key={String(t)}><I className="text-brand"/><b className="mt-4 block">{String(t)}</b><small className="text-slate-400">{String(d)}</small></Link>)}</div><div className="mt-8 rounded-xl border border-blue-100 bg-blue-50 p-5 text-sm text-blue-800">Hubungkan Supabase Auth untuk menampilkan data akun nyata. Tampilan saat ini adalah mode demo.</div></section>}
export function Orders(){return <section className="section container"><h1 className="text-4xl font-black">Riwayat Pesanan</h1><div className="mt-8 card overflow-hidden"><div className="grid grid-cols-3 bg-slate-50 p-4 text-xs font-bold"><span>Pesanan</span><span>Status</span><span>Total</span></div><div className="p-10 text-center text-slate-500">Belum ada pesanan terverifikasi.</div></div></section>}
export function DownloadPage(){return <section className="section container max-w-2xl text-center"><Download className="mx-auto text-brand" size={52}/><h1 className="mt-5 text-3xl font-black">Akses Download Aman</h1><p className="mt-3 text-slate-500">Masuk atau gunakan magic link dari email pembelian. Server akan memverifikasi kepemilikan dan membuat signed URL sementara.</p><Link to="/masuk" className="btn btn-primary mt-6">Masuk ke Akun</Link></section>}
export function NotFound(){return <section className="section container text-center"><span className="text-8xl font-black text-blue-100">404</span><h1 className="mt-3 text-3xl font-black">Halaman tidak ditemukan</h1><p className="mt-3 text-slate-500">Tautan mungkin berubah atau sudah tidak tersedia.</p><Link className="btn btn-primary mt-6" to="/">Kembali ke Beranda</Link></section>}
